version: '3.8'

services:
  jtinova:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: jtinova
    volumes:
      - ./:/var/www/html
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jtinova
    networks:
      - default

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - default

networks:
  default:
    name: jtinova

volumes:
  mysql:
    name: mysql
  