FROM php:8.3-fpm-alpine

RUN apk update && apk add --no-cache libzip-dev
RUN docker-php-ext-install pdo pdo_mysql zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

CMD ["php-fpm"]
