version: '3.8'

services:
  jtinova_staging:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: jtinova_staging
    volumes:
      - ./:/var/www/html
    networks:
      - default

  nginx_jtinova_staging:
    image: nginx:alpine
    container_name: nginx_jtinova_staging
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jtinova_staging
    networks:
      - default

networks:
  default:
    name: jtinova_staging_network